Repository deislabs/duffle, pull requests merged in 2019-03, with the labels that each got.

#652 Update readme with release and few notes
  README.md
Labels: docs

#612 feat: use Canonical JSON
  Gopkg.lock
  Gopkg.toml
  cmd/duffle/create_test.go
  pkg/bundle/bundle.go
  pkg/driver/driver.go
  pkg/duffle/manifest/create.go
  pkg/signature/signature.go
Labels: enhancement, review

#630 Add support for stateless actions
  pkg/action/action.go
  pkg/action/action_test.go
  pkg/action/install.go
  pkg/action/run_custom.go
  pkg/action/status.go
  pkg/action/uninstall.go
  pkg/action/upgrade.go
  pkg/bundle/bundle.go
  pkg/credentials/credentialset.go
  pkg/credentials/credentialset_test.go
Labels: review

#677 Re-enable azure pipelines
  azure-pipelines.yml
Labels: review

#679 chore(brigade.js): update Kashti build URL
  brigade.js
Labels: review
